CREATE TABLE IF NOT EXISTS
	performance ( 
		id						INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
		show					VARCHAR(255) NOT NULL,
		perfDateTime			DATETIME NOT NULL,
		twofer					TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
		preSold					TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
		soldOut					TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
		visible					TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
		comment					TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
		tixPriceAdult			TINYINT(1) UNSIGNED NOT NULL DEFAULT 20,
		tixPriceSeniorStudent	TINYINT(1) UNSIGNED NOT NULL DEFAULT 17
);
